services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3400:3000"  # <--- CORREGIDO: Mapea el 3400 local al 3000 interno de Next.js
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
