--
-- PostgreSQL database dump
--

\restrict HbDNpbQGzschzrDdYjtAt0NjNLVc4Q0djgvRJfacxQknA75c3RXKdFl92M9vssk

-- Dumped from database version 17.11 (32e7196)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Roles" (
    id_rol integer NOT NULL,
    nombre_rol character varying(100) NOT NULL
);


--
-- Name: Roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Roles" ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_id_rol_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: categorias_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversacion_participantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversacion_participantes (
    id_conversacion integer NOT NULL,
    id_usuario integer NOT NULL
);


--
-- Name: conversaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversaciones (
    id_conversacion integer NOT NULL,
    id_pedido integer NOT NULL,
    creada_en timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: conversaciones_id_conversacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversaciones ALTER COLUMN id_conversacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversaciones_id_conversacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalles_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.detalles_pedido (
    id_detalle_pedido integer NOT NULL,
    id_pedido integer NOT NULL,
    id_inventario integer NOT NULL,
    cantidad real NOT NULL,
    precio_unitario real NOT NULL,
    subtotal numeric NOT NULL
);


--
-- Name: detalles_pedido_id_detalle_pedido_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.detalles_pedido ALTER COLUMN id_detalle_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalles_pedido_id_detalle_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: impacto_social; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.impacto_social (
    id_impacto integer NOT NULL,
    id_proveedor integer NOT NULL,
    id_pedido integer NOT NULL,
    id_detalle_pedido integer NOT NULL,
    productos_salvados real NOT NULL,
    beneficio_extra_productor real NOT NULL,
    fecha_registro timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


--
-- Name: impacto_social_id_impacto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.impacto_social ALTER COLUMN id_impacto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.impacto_social_id_impacto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_proveedor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_proveedor (
    id_inventario integer NOT NULL,
    id_proveedor integer NOT NULL,
    id_producto integer NOT NULL,
    foto_url text,
    video_url text,
    stock_actual real NOT NULL,
    costo_produccion numeric NOT NULL,
    precio_venta numeric NOT NULL,
    es_oferta_excedente boolean DEFAULT false NOT NULL,
    porcentaje_descuento real,
    fecha_cosecha timestamp with time zone,
    disponible boolean DEFAULT true NOT NULL
);


--
-- Name: inventario_proveedor_id_inventario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventario_proveedor ALTER COLUMN id_inventario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_proveedor_id_inventario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logistica_entregas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logistica_entregas (
    id_entrega integer NOT NULL,
    id_pedido integer NOT NULL,
    id_usuario_repartidor integer NOT NULL,
    estado_actual text,
    ubicacion_actual text,
    fecha_estimada timestamp with time zone,
    fecha_entrega_real timestamp with time zone
);


--
-- Name: logistica_entregas_id_entrega_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logistica_entregas ALTER COLUMN id_entrega ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logistica_entregas_id_entrega_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensajes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensajes (
    id_mensaje integer NOT NULL,
    id_conversacion integer NOT NULL,
    id_emisor integer NOT NULL,
    contenido text NOT NULL,
    enviado_en timestamp with time zone DEFAULT now() NOT NULL,
    leido boolean DEFAULT false NOT NULL
);


--
-- Name: mensajes_id_mensaje_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensajes ALTER COLUMN id_mensaje ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensajes_id_mensaje_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones_entrega; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificaciones_entrega (
    id_notificacion integer NOT NULL,
    id_pedido integer NOT NULL,
    id_usuario_repartidor integer NOT NULL,
    zona_entrega character varying(200) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL
);


--
-- Name: notificaciones_entrega_id_notificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notificaciones_entrega_id_notificacion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notificaciones_entrega_id_notificacion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notificaciones_entrega_id_notificacion_seq OWNED BY public.notificaciones_entrega.id_notificacion;


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id_pedido integer NOT NULL,
    id_usuario_cliente integer NOT NULL,
    fecha_pedido timestamp with time zone NOT NULL,
    total numeric NOT NULL,
    metodo_pago text,
    estado_pago text,
    estado_envio text
);


--
-- Name: pedidos_id_pedido_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ALTER COLUMN id_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    id_permiso integer NOT NULL,
    nombre_permiso text NOT NULL
);


--
-- Name: permisos_id_permiso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos ALTER COLUMN id_permiso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos (
    id_producto integer NOT NULL,
    id_categoria integer NOT NULL,
    id_proveedor integer NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    unidad_medida character varying(50) NOT NULL
);


--
-- Name: productos_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedores (
    id_proveedor integer NOT NULL,
    id_usuario integer NOT NULL,
    nombre_proveedor character varying(150) NOT NULL,
    nombre_finca character varying(150),
    ubicacion_gps text,
    biografia text,
    calificacion_promedio real,
    banco text,
    cuenta_bancaria text
);


--
-- Name: proveedores_id_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proveedores ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedores_id_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registros_transferencia_mock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_transferencia_mock (
    id_transferencia character varying(64) NOT NULL,
    id_pedido integer NOT NULL,
    proveedor character varying(150) NOT NULL,
    banco_destino character varying(100) NOT NULL,
    cuenta character varying(100) NOT NULL,
    monto_enviado numeric(18,2) NOT NULL,
    estado character varying(50) NOT NULL
);


--
-- Name: repartidor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repartidor (
    id integer NOT NULL,
    id_usuario integer NOT NULL,
    placa_vehiculo text NOT NULL,
    estado text NOT NULL,
    vehiculo text NOT NULL,
    promedio_calificacion numeric NOT NULL,
    cuenta_bancaria text NOT NULL,
    url_foto_perfil text NOT NULL,
    zona_operaciones text NOT NULL
);


--
-- Name: repartidor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.repartidor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repartidor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_permisos (
    id_rol integer NOT NULL,
    id_permisos integer NOT NULL
);


--
-- Name: solicitud_repartidor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitud_repartidor (
    id_solicitud integer NOT NULL,
    id_usuario integer NOT NULL,
    datos_repartidor jsonb NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_solicitud timestamp with time zone NOT NULL
);


--
-- Name: solicitud_repartidor_id_solicitud_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solicitud_repartidor ALTER COLUMN id_solicitud ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitud_repartidor_id_solicitud_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suscripciones_app; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suscripciones_app (
    id_suscripcion_app integer NOT NULL,
    id_usuario integer NOT NULL,
    tipo_plan text NOT NULL,
    tarifa_pago numeric NOT NULL,
    estado text,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone,
    renovacion_automatica boolean DEFAULT true NOT NULL,
    creada_en timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: suscripciones_app_id_suscripcion_app_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suscripciones_app ALTER COLUMN id_suscripcion_app ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suscripciones_app_id_suscripcion_app_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    nombre_completo character varying(200) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text,
    identidad_verificada boolean NOT NULL,
    o_auth_provider text,
    o_auth_provider_id text,
    telefono text,
    direccion_base text,
    fecha_registro timestamp with time zone,
    departamento character varying(255),
    estado_cuenta text DEFAULT 'Activo'::text
);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_roles (
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL
);


--
-- Name: valoraciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.valoraciones (
    id_valoracion integer NOT NULL,
    id_pedido integer NOT NULL,
    id_usuario_cliente integer NOT NULL,
    tipo_valoracion text,
    puntuacion integer NOT NULL,
    comentario text,
    fecha_valoracion timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    id_proveedor integer DEFAULT 0 NOT NULL
);


--
-- Name: valoraciones_id_valoracion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.valoraciones ALTER COLUMN id_valoracion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.valoraciones_id_valoracion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones_entrega id_notificacion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones_entrega ALTER COLUMN id_notificacion SET DEFAULT nextval('public.notificaciones_entrega_id_notificacion_seq'::regclass);


--
-- Name: notificaciones_entrega notificaciones_entrega_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones_entrega
    ADD CONSTRAINT notificaciones_entrega_pkey PRIMARY KEY (id_notificacion);


--
-- Name: __EFMigrationsHistory pk___ef_migrations_history; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id);


--
-- Name: categorias pk_categorias; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT pk_categorias PRIMARY KEY (id_categoria);


--
-- Name: conversacion_participantes pk_conversacion_participantes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversacion_participantes
    ADD CONSTRAINT pk_conversacion_participantes PRIMARY KEY (id_conversacion, id_usuario);


--
-- Name: conversaciones pk_conversaciones; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT pk_conversaciones PRIMARY KEY (id_conversacion);


--
-- Name: detalles_pedido pk_detalles_pedido; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT pk_detalles_pedido PRIMARY KEY (id_detalle_pedido);


--
-- Name: impacto_social pk_impacto_social; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impacto_social
    ADD CONSTRAINT pk_impacto_social PRIMARY KEY (id_impacto);


--
-- Name: inventario_proveedor pk_inventario_proveedor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_proveedor
    ADD CONSTRAINT pk_inventario_proveedor PRIMARY KEY (id_inventario);


--
-- Name: logistica_entregas pk_logistica_entregas; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logistica_entregas
    ADD CONSTRAINT pk_logistica_entregas PRIMARY KEY (id_entrega);


--
-- Name: mensajes pk_mensajes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT pk_mensajes PRIMARY KEY (id_mensaje);


--
-- Name: pedidos pk_pedidos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pk_pedidos PRIMARY KEY (id_pedido);


--
-- Name: permisos pk_permisos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT pk_permisos PRIMARY KEY (id_permiso);


--
-- Name: productos pk_productos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT pk_productos PRIMARY KEY (id_producto);


--
-- Name: proveedores pk_proveedores; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT pk_proveedores PRIMARY KEY (id_proveedor);


--
-- Name: repartidor pk_repartidor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repartidor
    ADD CONSTRAINT pk_repartidor PRIMARY KEY (id);


--
-- Name: Roles pk_roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT pk_roles PRIMARY KEY (id_rol);


--
-- Name: roles_permisos pk_roles_permisos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT pk_roles_permisos PRIMARY KEY (id_rol, id_permisos);


--
-- Name: solicitud_repartidor pk_solicitud_repartidor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_repartidor
    ADD CONSTRAINT pk_solicitud_repartidor PRIMARY KEY (id_solicitud);


--
-- Name: suscripciones_app pk_suscripciones_app; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suscripciones_app
    ADD CONSTRAINT pk_suscripciones_app PRIMARY KEY (id_suscripcion_app);


--
-- Name: usuarios pk_usuarios; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario);


--
-- Name: usuarios_roles pk_usuarios_roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_roles
    ADD CONSTRAINT pk_usuarios_roles PRIMARY KEY (id_usuario, id_rol);


--
-- Name: valoraciones pk_valoraciones; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoraciones
    ADD CONSTRAINT pk_valoraciones PRIMARY KEY (id_valoracion);


--
-- Name: registros_transferencia_mock registros_transferencia_mock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_transferencia_mock
    ADD CONSTRAINT registros_transferencia_mock_pkey PRIMARY KEY (id_transferencia);


--
-- Name: ix_conversacion_participantes_id_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_conversacion_participantes_id_usuario ON public.conversacion_participantes USING btree (id_usuario);


--
-- Name: ix_conversaciones_id_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_conversaciones_id_pedido ON public.conversaciones USING btree (id_pedido);


--
-- Name: ix_detalles_pedido_id_inventario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_detalles_pedido_id_inventario ON public.detalles_pedido USING btree (id_inventario);


--
-- Name: ix_detalles_pedido_id_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_detalles_pedido_id_pedido ON public.detalles_pedido USING btree (id_pedido);


--
-- Name: ix_impacto_social_id_detalle_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_impacto_social_id_detalle_pedido ON public.impacto_social USING btree (id_detalle_pedido);


--
-- Name: ix_impacto_social_id_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_impacto_social_id_pedido ON public.impacto_social USING btree (id_pedido);


--
-- Name: ix_impacto_social_id_proveedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_impacto_social_id_proveedor ON public.impacto_social USING btree (id_proveedor);


--
-- Name: ix_inventario_proveedor_id_producto; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_inventario_proveedor_id_producto ON public.inventario_proveedor USING btree (id_producto);


--
-- Name: ix_inventario_proveedor_id_proveedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_inventario_proveedor_id_proveedor ON public.inventario_proveedor USING btree (id_proveedor);


--
-- Name: ix_logistica_entregas_id_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_logistica_entregas_id_pedido ON public.logistica_entregas USING btree (id_pedido);


--
-- Name: ix_logistica_entregas_id_usuario_repartidor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_logistica_entregas_id_usuario_repartidor ON public.logistica_entregas USING btree (id_usuario_repartidor);


--
-- Name: ix_mensajes_id_conversacion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_mensajes_id_conversacion ON public.mensajes USING btree (id_conversacion);


--
-- Name: ix_mensajes_id_emisor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_mensajes_id_emisor ON public.mensajes USING btree (id_emisor);


--
-- Name: ix_pedidos_id_usuario_cliente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pedidos_id_usuario_cliente ON public.pedidos USING btree (id_usuario_cliente);


--
-- Name: ix_productos_id_categoria; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_productos_id_categoria ON public.productos USING btree (id_categoria);


--
-- Name: ix_productos_id_proveedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_productos_id_proveedor ON public.productos USING btree (id_proveedor);


--
-- Name: ix_proveedores_id_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_proveedores_id_usuario ON public.proveedores USING btree (id_usuario);


--
-- Name: ix_repartidor_id_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_repartidor_id_usuario ON public.repartidor USING btree (id_usuario);


--
-- Name: ix_roles_permisos_id_permisos; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_roles_permisos_id_permisos ON public.roles_permisos USING btree (id_permisos);


--
-- Name: ix_solicitud_repartidor_id_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_solicitud_repartidor_id_usuario ON public.solicitud_repartidor USING btree (id_usuario);


--
-- Name: ix_suscripciones_app_id_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_suscripciones_app_id_usuario ON public.suscripciones_app USING btree (id_usuario);


--
-- Name: ix_usuarios_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_usuarios_email ON public.usuarios USING btree (email);


--
-- Name: ix_usuarios_roles_id_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_usuarios_roles_id_rol ON public.usuarios_roles USING btree (id_rol);


--
-- Name: ix_valoraciones_id_pedido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_valoraciones_id_pedido ON public.valoraciones USING btree (id_pedido);


--
-- Name: ix_valoraciones_id_proveedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_valoraciones_id_proveedor ON public.valoraciones USING btree (id_proveedor);


--
-- Name: ix_valoraciones_id_usuario_cliente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_valoraciones_id_usuario_cliente ON public.valoraciones USING btree (id_usuario_cliente);


--
-- Name: conversacion_participantes fk_conversacion_participantes_conversaciones_id_conversacion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversacion_participantes
    ADD CONSTRAINT fk_conversacion_participantes_conversaciones_id_conversacion FOREIGN KEY (id_conversacion) REFERENCES public.conversaciones(id_conversacion) ON DELETE CASCADE;


--
-- Name: conversacion_participantes fk_conversacion_participantes_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversacion_participantes
    ADD CONSTRAINT fk_conversacion_participantes_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: conversaciones fk_conversaciones_pedidos_id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT fk_conversaciones_pedidos_id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON DELETE CASCADE;


--
-- Name: detalles_pedido fk_detalles_pedido_inventario_proveedor_id_inventario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT fk_detalles_pedido_inventario_proveedor_id_inventario FOREIGN KEY (id_inventario) REFERENCES public.inventario_proveedor(id_inventario) ON DELETE CASCADE;


--
-- Name: detalles_pedido fk_detalles_pedido_pedidos_id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT fk_detalles_pedido_pedidos_id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON DELETE CASCADE;


--
-- Name: impacto_social fk_impacto_social_detalles_pedido_id_detalle_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impacto_social
    ADD CONSTRAINT fk_impacto_social_detalles_pedido_id_detalle_pedido FOREIGN KEY (id_detalle_pedido) REFERENCES public.detalles_pedido(id_detalle_pedido) ON DELETE CASCADE;


--
-- Name: impacto_social fk_impacto_social_pedidos_id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impacto_social
    ADD CONSTRAINT fk_impacto_social_pedidos_id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON DELETE CASCADE;


--
-- Name: impacto_social fk_impacto_social_proveedores_id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.impacto_social
    ADD CONSTRAINT fk_impacto_social_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id_proveedor) ON DELETE CASCADE;


--
-- Name: inventario_proveedor fk_inventario_proveedor_productos_id_producto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_proveedor
    ADD CONSTRAINT fk_inventario_proveedor_productos_id_producto FOREIGN KEY (id_producto) REFERENCES public.productos(id_producto) ON DELETE CASCADE;


--
-- Name: inventario_proveedor fk_inventario_proveedor_proveedores_id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_proveedor
    ADD CONSTRAINT fk_inventario_proveedor_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id_proveedor) ON DELETE CASCADE;


--
-- Name: logistica_entregas fk_logistica_entregas_pedidos_id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logistica_entregas
    ADD CONSTRAINT fk_logistica_entregas_pedidos_id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON DELETE CASCADE;


--
-- Name: logistica_entregas fk_logistica_entregas_usuarios_id_usuario_repartidor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logistica_entregas
    ADD CONSTRAINT fk_logistica_entregas_usuarios_id_usuario_repartidor FOREIGN KEY (id_usuario_repartidor) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: mensajes fk_mensajes_conversaciones_id_conversacion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_conversaciones_id_conversacion FOREIGN KEY (id_conversacion) REFERENCES public.conversaciones(id_conversacion) ON DELETE CASCADE;


--
-- Name: mensajes fk_mensajes_usuarios_id_emisor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_usuarios_id_emisor FOREIGN KEY (id_emisor) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: pedidos fk_pedidos_usuarios_id_usuario_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_usuarios_id_usuario_cliente FOREIGN KEY (id_usuario_cliente) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: productos fk_productos_categorias_id_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_categorias_id_categoria FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria) ON DELETE CASCADE;


--
-- Name: productos fk_productos_proveedores_id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id_proveedor) ON DELETE CASCADE;


--
-- Name: proveedores fk_proveedores_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT fk_proveedores_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: repartidor fk_repartidor_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repartidor
    ADD CONSTRAINT fk_repartidor_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: roles_permisos fk_roles_permisos_permisos_id_permisos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT fk_roles_permisos_permisos_id_permisos FOREIGN KEY (id_permisos) REFERENCES public.permisos(id_permiso) ON DELETE CASCADE;


--
-- Name: roles_permisos fk_roles_permisos_roles_id_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT fk_roles_permisos_roles_id_rol FOREIGN KEY (id_rol) REFERENCES public."Roles"(id_rol) ON DELETE CASCADE;


--
-- Name: solicitud_repartidor fk_solicitud_repartidor_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_repartidor
    ADD CONSTRAINT fk_solicitud_repartidor_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: suscripciones_app fk_suscripciones_app_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suscripciones_app
    ADD CONSTRAINT fk_suscripciones_app_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: usuarios_roles fk_usuarios_roles_roles_id_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_roles_id_rol FOREIGN KEY (id_rol) REFERENCES public."Roles"(id_rol) ON DELETE CASCADE;


--
-- Name: usuarios_roles fk_usuarios_roles_usuarios_id_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_usuarios_id_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- Name: valoraciones fk_valoraciones_pedidos_id_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoraciones
    ADD CONSTRAINT fk_valoraciones_pedidos_id_pedido FOREIGN KEY (id_pedido) REFERENCES public.pedidos(id_pedido) ON DELETE CASCADE;


--
-- Name: valoraciones fk_valoraciones_proveedores_id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoraciones
    ADD CONSTRAINT fk_valoraciones_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id_proveedor) ON DELETE CASCADE;


--
-- Name: valoraciones fk_valoraciones_usuarios_id_usuario_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.valoraciones
    ADD CONSTRAINT fk_valoraciones_usuarios_id_usuario_cliente FOREIGN KEY (id_usuario_cliente) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict HbDNpbQGzschzrDdYjtAt0NjNLVc4Q0djgvRJfacxQknA75c3RXKdFl92M9vssk

