// <auto-generated />
using System;
using Meseta_Verde.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meseta_Verde.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MesetaVerdeDbContext))]
    partial class MesetaVerdeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Conversacion", b =>
                {
                    b.Property<int>("IdConversacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_conversacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConversacion"));

                    b.Property<DateTime>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.HasKey("IdConversacion")
                        .HasName("pk_conversaciones");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_conversaciones_id_pedido");

                    b.ToTable("conversaciones", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.ConversacionParticipante", b =>
                {
                    b.Property<int>("IdConversacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_conversacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdConversacion", "IdUsuario")
                        .HasName("pk_conversacion_participantes");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_conversacion_participantes_id_usuario");

                    b.ToTable("conversacion_participantes", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<float>("Cantidad")
                        .HasColumnType("real")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdInventario")
                        .HasColumnType("integer")
                        .HasColumnName("id_inventario");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<float>("PrecioUnitario")
                        .HasColumnType("real")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetallePedido")
                        .HasName("pk_detalles_pedido");

                    b.HasIndex("IdInventario")
                        .HasDatabaseName("ix_detalles_pedido_id_inventario");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_detalles_pedido_id_pedido");

                    b.ToTable("detalles_pedido", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.ImpactoSocial", b =>
                {
                    b.Property<int>("IdImpacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_impacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImpacto"));

                    b.Property<float>("BeneficioExtraProductor")
                        .HasColumnType("real")
                        .HasColumnName("beneficio_extra_productor");

                    b.Property<int>("IdDetallePedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_pedido");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<float>("ProductosSalvados")
                        .HasColumnType("real")
                        .HasColumnName("productos_salvados");

                    b.HasKey("IdImpacto")
                        .HasName("pk_impacto_social");

                    b.HasIndex("IdDetallePedido")
                        .HasDatabaseName("ix_impacto_social_id_detalle_pedido");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_impacto_social_id_pedido");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("ix_impacto_social_id_proveedor");

                    b.ToTable("impacto_social", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.InventarioProveedor", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_inventario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInventario"));

                    b.Property<decimal>("CostoProduccion")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_produccion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<bool>("EsOfertaExcedente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_oferta_excedente");

                    b.Property<DateTime?>("FechaCosecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cosecha");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<float?>("PorcentajeDescuento")
                        .HasColumnType("real")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_venta");

                    b.Property<float>("StockActual")
                        .HasColumnType("real")
                        .HasColumnName("stock_actual");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("IdInventario")
                        .HasName("pk_inventario_proveedor");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_inventario_proveedor_id_producto");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("ix_inventario_proveedor_id_proveedor");

                    b.ToTable("inventario_proveedor", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.LogisticaEntrega", b =>
                {
                    b.Property<int>("IdEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_entrega");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntrega"));

                    b.Property<string>("EstadoActual")
                        .HasColumnType("text")
                        .HasColumnName("estado_actual");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega_real");

                    b.Property<DateTime?>("FechaEstimada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_estimada");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdUsuarioRepartidor")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_repartidor");

                    b.Property<string>("UbicacionActual")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion_actual");

                    b.HasKey("IdEntrega")
                        .HasName("pk_logistica_entregas");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_logistica_entregas_id_pedido");

                    b.HasIndex("IdUsuarioRepartidor")
                        .HasDatabaseName("ix_logistica_entregas_id_usuario_repartidor");

                    b.ToTable("logistica_entregas", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mensaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMensaje"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("EnviadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdConversacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_conversacion");

                    b.Property<int>("IdUsuarioEmisor")
                        .HasColumnType("integer")
                        .HasColumnName("id_emisor");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leido");

                    b.HasKey("IdMensaje")
                        .HasName("pk_mensajes");

                    b.HasIndex("IdConversacion")
                        .HasDatabaseName("ix_mensajes_id_conversacion");

                    b.HasIndex("IdUsuarioEmisor")
                        .HasDatabaseName("ix_mensajes_id_emisor");

                    b.ToTable("mensajes", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("EstadoEnvio")
                        .HasColumnType("text")
                        .HasColumnName("estado_envio");

                    b.Property<string>("EstadoPago")
                        .HasColumnType("text")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<int>("IdUsuarioCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cliente");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("IdPedido")
                        .HasName("pk_pedidos");

                    b.HasIndex("IdUsuarioCliente")
                        .HasDatabaseName("ix_pedidos_id_usuario_cliente");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("IdPermiso")
                        .HasName("pk_permisos");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdProducto")
                        .HasName("pk_productos");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("ix_productos_id_categoria");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("ix_productos_id_proveedor");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<float?>("CalificacionPromedio")
                        .HasColumnType("real")
                        .HasColumnName("calificacion_promedio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreFinca")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_finca");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_proveedor");

                    b.Property<string>("UbicacionGps")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion_gps");

                    b.HasKey("IdProveedor")
                        .HasName("pk_proveedores");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_proveedores_id_usuario");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("pk_roles");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermisos")
                        .HasColumnType("integer")
                        .HasColumnName("id_permisos");

                    b.HasKey("IdRol", "IdPermisos")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("IdPermisos")
                        .HasDatabaseName("ix_roles_permisos_id_permisos");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.SuscripcionApp", b =>
                {
                    b.Property<int>("IdSuscripcionApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_suscripcion_app");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuscripcionApp"));

                    b.Property<DateTime>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("RenovacionAutomatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("renovacion_automatica");

                    b.Property<decimal>("TarifaPago")
                        .HasColumnType("numeric")
                        .HasColumnName("tarifa_pago");

                    b.Property<string>("TipoPlan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_plan");

                    b.HasKey("IdSuscripcionApp")
                        .HasName("pk_suscripciones_app");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_suscripciones_app_id_usuario");

                    b.ToTable("suscripciones_app", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("DireccionBase")
                        .HasColumnType("text")
                        .HasColumnName("direccion_base");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<bool>("IdentidadVerificada")
                        .HasColumnType("boolean")
                        .HasColumnName("identidad_verificada");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("OAuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("o_auth_provider");

                    b.Property<string>("OAuthProviderId")
                        .HasColumnType("text")
                        .HasColumnName("o_auth_provider_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("ix_usuarios_roles_id_rol");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Valoracion", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_valoracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdValoracion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdUsuarioCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cliente");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer")
                        .HasColumnName("puntuacion");

                    b.Property<string>("TipoValoracion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_valoracion");

                    b.HasKey("IdValoracion")
                        .HasName("pk_valoraciones");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_valoraciones_id_pedido");

                    b.HasIndex("IdUsuarioCliente")
                        .HasDatabaseName("ix_valoraciones_id_usuario_cliente");

                    b.ToTable("valoraciones", (string)null);
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Conversacion", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversaciones_pedidos_id_pedido");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.ConversacionParticipante", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Participantes")
                        .HasForeignKey("IdConversacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversacion_participantes_conversaciones_id_conversacion");

                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ConversacionParticipantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversacion_participantes_usuarios_id_usuario");

                    b.Navigation("Conversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.InventarioProveedor", "Inventario")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdInventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_pedido_inventario_proveedor_id_inventario");

                    b.HasOne("Meseta_Verda.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_pedido_pedidos_id_pedido");

                    b.Navigation("Inventario");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.ImpactoSocial", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.DetallePedido", "DetallePedido")
                        .WithMany()
                        .HasForeignKey("IdDetallePedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_impacto_social_detalles_pedido_id_detalle_pedido");

                    b.HasOne("Meseta_Verda.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_impacto_social_pedidos_id_pedido");

                    b.HasOne("Meseta_Verda.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_impacto_social_proveedores_id_proveedor");

                    b.Navigation("DetallePedido");

                    b.Navigation("Pedido");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.InventarioProveedor", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_proveedor_productos_id_producto");

                    b.HasOne("Meseta_Verda.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_proveedor_proveedores_id_proveedor");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.LogisticaEntrega", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logistica_entregas_pedidos_id_pedido");

                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "UsuarioRepartidor")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRepartidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logistica_entregas_usuarios_id_usuario_repartidor");

                    b.Navigation("Pedido");

                    b.Navigation("UsuarioRepartidor");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("IdConversacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_conversaciones_id_conversacion");

                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEmisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_usuarios_id_emisor");

                    b.Navigation("Conversacion");

                    b.Navigation("Emisor");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "UsuarioCliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_id_usuario_cliente");

                    b.Navigation("UsuarioCliente");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_id_categoria");

                    b.HasOne("Meseta_Verda.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_proveedores_id_proveedor");

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proveedores_usuarios_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermisos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_id_permisos");

                    b.HasOne("Meseta_Verda.Domain.Entities.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_id_rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.SuscripcionApp", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suscripciones_app_usuarios_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_id_rol");

                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_id_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Valoracion", b =>
                {
                    b.HasOne("Meseta_Verda.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_valoraciones_pedidos_id_pedido");

                    b.HasOne("Meseta_Verda.Domain.Entities.Usuario", "UsuarioCliente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_valoraciones_usuarios_id_usuario_cliente");

                    b.Navigation("Pedido");

                    b.Navigation("UsuarioCliente");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.InventarioProveedor", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Meseta_Verda.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ConversacionParticipantes");

                    b.Navigation("Pedidos");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
