<Project Sdk="Microsoft.NET.Sdk"> <!-- Cambiado a .Sdk.Web para incluir las APIs de ASP.NET Core automáticamente -->

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>


  <ItemGroup>
    <Compile Remove="Common\DTOs\SolicitudesRoles\**" />
    <EmbeddedResource Remove="Common\DTOs\SolicitudesRoles\**" />
    <None Remove="Common\DTOs\SolicitudesRoles\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Exception\" />
    <Folder Include="Features\CuentasBancarias\Queries\" />
    <Folder Include="Features\Pedidos\CarritoServices\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" /> <!-- Reemplazo de la referencia manual -->
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.GenAI" Version="1.21.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agro_Trade.Domain\Agro_Trade.Domain.csproj" />
  </ItemGroup>

</Project>
